### ISSUE TITLE
Error running on Debian 9.9 with Yunohost 3.5.2.2

### ISSUE THREAD

**Issue by ImaCrea** [cavebeat/gandi-live-dns#29]
Hello, thanks for your work. Unfotunately I can't make it work on my side :/
I'm trying to point ziad.io which I bought on Gandi to my homeserver.

# What I get
```
root@ziad:~/gandi-live-dns/src# ./gandi-live-dns.py 
Traceback (most recent call last):
  File "./gandi-live-dns.py", line 124, in <module>
    main(args.force, args.verbose)
  File "./gandi-live-dns.py", line 102, in main
    dynIP = get_dynip(config.ifconfig)
  File "./gandi-live-dns.py", line 24, in get_dynip
    r = requests.get(ifconfig_provider)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 366, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'choose_from_above_or_run_your_own': No schema supplied. Perhaps you meant http://choose_from_above_or_run_your_own?
root@ziad:~/gandi-live-dns/src# 

```
# My config.py
```
'''
Created on 13 Aug 2017
@author: cave
Copy this file to config.py and update the settings
'''
#!/usr/bin/env python
# encoding: utf-8

'''
Get your API key
Start by retrieving your API Key from the "Security" section in new Account admin panel to be able to make authenticated requests to the API.
https://account.gandi.net/
'''
api_secret = 'xxxxxxx' 

'''
Gandiv5 LiveDNS API Location
http://doc.livedns.gandi.net/#api-endpoint
https://dns.api.gandi.net/api/v5/
'''
api_endpoint = 'https://dns.api.gandi.net/api/v5'

#your domain with the subdomains in the zone file/UUID 
domain = 'ziad.io'

#enter all subdomains to be updated, subdomains must already exist to be updated
subdomains = ["www"]

#300 seconds = 5 minutes
ttl = '300'

''' 
IP address lookup service 
run your own external IP provider:
+ https://github.com/mpolden/ipd
+ <?php $ip = $_SERVER['REMOTE_ADDR']; ?>
  <?php print $ip; ?>
e.g. 
+ https://ifconfig.co/ip
+ http://ifconfig.me/ip
+ http://whatismyip.akamai.com/
+ http://ipinfo.io/ip
+ many more ...
'''
ifconfig = 'choose_from_above_or_run_your_own'

```

Please help :)

**Comment by sevseux** [comment]
Hi,

You should change the default value for the ifconfig variable :)

**Comment by ImaCrea** [comment]
Hi @sevseux thank you for your very quick answer!
It works better in deed but I get stuck to the next step. I've put "www" in subdomain but I don't really have it configured in my dns record :/ I just want to point to the domain.ltd with no subdomain. 

Is that possible with that script please ?

```
Checking dynamic IP:  109.14.60.123
Error: HTTP Status Code  404 when trying to get IP from subdomain www
Traceback (most recent call last):
  File "./gandi-live-dns.py", line 124, in <module>
    main(args.force, args.verbose)
  File "./gandi-live-dns.py", line 103, in main
    dnsIP = get_dnsip(uuid)
  File "./gandi-live-dns.py", line 63, in get_dnsip
    print  json_object['message']
UnboundLocalError: local variable 'json_object' referenced before assignment
```

**Comment by ImaCrea** [comment]
Ok looks like it's working if I put "@" in subdomain !
Yay !! Thanks for your dear help on a Friday night @sevseux :)

**Comment by ImaCrea** [comment]
I close the issue :)
