### ISSUE TITLE
cron.hourly / gandi-live-dns.py error

### ISSUE THREAD

**Issue by hemertje** [cavebeat/gandi-live-dns#37]
On my Debian / OpenMediaVault Pine64 RockPro installation

nano /etc/cron.hourly/dns-update

`/root/gandi-live-dns/src/gandi-live-dns.py >/dev/null 2>&1`

Email-notification:

```
/etc/cron.hourly/dns-update:
run-parts: failed to exec /etc/cron.hourly/dns-update: Exec format error
run-parts: /etc/cron.hourly/dns-update exited with return code 1
```

When I run the command manual:

```
root@X:~/gandi-live-dns# /root/gandi-live-dns/src/gandi-live-dns.py
Checking dynamic IP:  X.X.X.X
Error: HTTP Status Code  404 when trying to get IP from subdomain home
Traceback (most recent call last):
  File "/root/gandi-live-dns/src/gandi-live-dns.py", line 124, in <module>
    main(args.force, args.verbose)
  File "/root/gandi-live-dns/src/gandi-live-dns.py", line 103, in main
    dnsIP = get_dnsip(uuid)
  File "/root/gandi-live-dns/src/gandi-live-dns.py", line 63, in get_dnsip
    print  json_object['message']
UnboundLocalError: local variable 'json_object' referenced before assignment
root@X:~/gandi-live-dns#
```

**Comment by hemertje** [comment]
my mistake, the checked subdomain 'home' didn't exist in the DNS registry ;)
now checking with *
